name: designatedlands
channels:
  - defaults
dependencies:
  - python=3.7.7
  - pip=20.0.2
  - requests=2.24.0
  - click=7.1.2
  - rasterio=1.1.0
  - numpy=1.19.1
  - affine=2.3.0
  - gdal=3.0.2
  - geos=3.8.0
  - geotiff=1.5.1
  - proj=6.2.1
  - fiona=1.8.13.post1
  - pandas==1.1.0
  - sqlalchemy==1.3.19
  - pip:
    - pgdata==0.0.12
    - bcdata==0.4.1
    - geoalchemy2==0.8.4
    - sqlalchemy-utils==0.36.8
